import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import ReactQueryProvider from "@/components/Providers/ReactQueryProvider";
import ReactReduxProvider from "@/components/Providers/ReactReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alemeno Education",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ReactReduxProvider>
        <ReactQueryProvider>
          <body className={inter.className}>
            {children}
          </body>
        </ReactQueryProvider>
      </ReactReduxProvider>
    </html>
  );
}
